menu:
  文章:
    隧道: /archives/ || anzhiyu-icon-box-archive
    分类: /categories/ || anzhiyu-icon-shapes
    标签: /tags/ || anzhiyu-icon-tags

  友链:
    友人帐: /link/ || anzhiyu-icon-link
    朋友圈: /fcircle/ || anzhiyu-icon-artstation
    留言板: /comments/ || anzhiyu-icon-envelope

  我的:
    音乐馆: /music/ || anzhiyu-icon-music
    追番页: /bangumis/ || anzhiyu-icon-bilibili
    相册集: /album/ || anzhiyu-icon-images
    小空调: /air-conditioner/ || anzhiyu-icon-fan

  关于:
    关于本人: /about/ || anzhiyu-icon-paper-plane
    闲言碎语: /essay/ || anzhiyu-icon-lightbulb
    随便逛逛: javascript:toRandomPost() || anzhiyu-icon-shoe-prints1

# Sponsor/reward
reward:
  enable: false
  QR_code:
    - img: https://你的二维码图片地址.png
      link: https://你的支付链接
      text: 微信

aside:
  card_author:
    enable: true
    description: "我是通天野马，一个热爱生活的前端开发者，喜欢分享技术和生活点滴。"
    name_link: "/about/"

category:
  -name: "开发"
      path: /categories/编程/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-code
  -name: "生活"
      path: /categories/生活/
      shadow: var(--anzhiyu-shadow-green)
      class: green
      icon: anzhiyu-icon-heart
  -name: "其他"
      path: /categories/其他/
      shadow: var(--anzhiyu-shadow-gray)
      class: gray
      icon: anzhiyu-icon-file